# Git Action Deploy
name: Deploy to Ubuntu Server

on:
  push:
    branches: 
    - main  # main branch에 push 될 때 트리거 (commit / push)
  
jobs:
  deploy:
    runs-on: ubuntu-latest # ubuntu 최종버전
    
    steps:
    # 코드 체크 아웃
    - name: Checkout repository
      uses: actions/checkout@v2

    # jdk 17 설정
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        
    # gradlew 권한 부여
    - name: Setup gradlew permissions
      run: |
        chmod +x ./gradlew

    # gradle build
    - name: Build with Gradle
      run: ./gradlew clean build -x test
    
    # war 파일생성 = clean 전체 삭제 => 다시 build
    - name: Login in to DockerHub
      run: |
        echo "${{secrets.DOCKERHUB_PASSWORD}}" | docker login -u "${{secrets.DOCKERHUB_USERNAME}}" --password-stdin
    - name: Build and Push Docker Image
      run: |
        docker build -t ${{secrets.DOCKERHUB_USERNAME}}/spring-boot-app:latest .
        docker push ${{secrets.DOCKERHUB_USERNAME}}/spring-boot-app:latest
    
    # SSH : 암호화 통신 => 개인키(id_ed25519)를 가지고 AWS에 접속
    - name: Add SSH Key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{secrets.SERVER_SSH_KEY}}
    # 등록 => 서버키 등록

    - name: Add known_hosts
      run: |
        ssh-keyscan -t ed25519 13.125.119.45 >> ~/.ssh/known_hosts
    # 실행
    # 정지 => docker stop image명
    # 삭제 => docker rm image명
    - name: Deploy on Server using DockerHub image
      run: |
        ssh ubuntu@13.125.119.45 << 'EOF'
          sudo docker stop spring-app || true
          sudo docker rm spring-app || true
          sudo docker pull ${{secrets.DOCKERHUB_USERNAME}}/spring-boot-app:latest
          sudo docker run -d --name spring-app --restart always -p 8080:8080 ${{secrets.DOCKERHUB_USERNAME}}/spring-boot-app:latest
        EOF
